'use strict';

/*
 * Self-contained backup/restore for this adapter instance (config, sensors, Data-SOLECTRUS
 * items and the object tree it creates). Reuses the approach validated in the SOLECTRUS
 * InfluxDB module of ioBroker.backitup (object-based backup, native-config-only instance
 * restore, exclude protectedNative fields) but stores backups locally so no other adapter
 * has to be installed.
 */

const fsp = require('node:fs/promises');
const path = require('node:path');
const zlib = require('node:zlib');

const { version: ADAPTER_VERSION } = require('../package.json');
const ioPack = require('../io-package.json');

const BACKUP_EXT = '.solectrusbackup.json.gz';
const PROTECTED_NATIVE_KEYS = ioPack.encryptedNative || [];
const DEFAULT_KEEP_COUNT = 5;

/**
 * Local directory this instance stores its own backups in. Defaults to a "backups"
 * subfolder of the instance's own data directory, but can be overridden by the user
 * (e.g. to point at a different disk or a mounted network share) via the "Backup
 * directory" field on the Backup tab. A relative custom path is resolved against the
 * instance's data directory; an absolute path is used as-is.
 *
 * @param {object} adapter - The ioBroker adapter instance.
 * @returns {string} Absolute path to the backup directory.
 */
function getBackupDir(adapter) {
	const customDir = adapter.config && String(adapter.config.backupDir || '').trim();
	if (!customDir) {
		return path.join(adapter.adapterDir, 'backups');
	}
	return path.isAbsolute(customDir) ? customDir : path.join(adapter.adapterDir, customDir);
}

async function ensureBackupDir(adapter) {
	const dir = getBackupDir(adapter);
	await fsp.mkdir(dir, { recursive: true });
	return dir;
}

/**
 * Only plain backup file names generated by this module are ever accepted back.
 *
 * @param {string} fileName - Candidate file name to validate.
 * @returns {string} The validated file name.
 */
function sanitizeFileName(fileName) {
	const base = path.basename(String(fileName || ''));
	if (!base || base !== fileName || !base.endsWith(BACKUP_EXT)) {
		throw new Error('Invalid backup file name');
	}
	return base;
}

/**
 * Lists all local backups for this instance, most recent first.
 *
 * @param {object} adapter - The ioBroker adapter instance.
 * @returns {Promise<Array<{fileName: string, size: number, mtime: number}>>} Backup file metadata.
 */
async function listBackups(adapter) {
	const dir = await ensureBackupDir(adapter);
	const entries = await fsp.readdir(dir);
	const backups = [];
	for (const fileName of entries) {
		if (!fileName.endsWith(BACKUP_EXT)) {
			continue;
		}
		try {
			const stat = await fsp.stat(path.join(dir, fileName));
			backups.push({ fileName, size: stat.size, mtime: stat.mtimeMs });
		} catch {
			// file disappeared/unreadable between readdir and stat - skip it
		}
	}
	backups.sort((a, b) => b.mtime - a.mtime);
	return backups;
}

async function pruneOldBackups(adapter) {
	const keepCount =
		Number.isFinite(adapter.config && adapter.config.backupKeepCount) && adapter.config.backupKeepCount > 0
			? adapter.config.backupKeepCount
			: DEFAULT_KEEP_COUNT;
	const dir = getBackupDir(adapter);
	const backups = await listBackups(adapter);
	for (const old of backups.slice(keepCount)) {
		try {
			await fsp.unlink(path.join(dir, old.fileName));
		} catch (err) {
			adapter.log.debug(`Could not prune old backup "${old.fileName}": ${err}`);
		}
	}
}

/**
 * Strips encrypted/protected native keys (e.g. influxToken) - never leave this instance.
 *
 * @param {object} native - The instance's native config.
 * @returns {object} A shallow copy without protected keys.
 */
function stripProtectedNative(native) {
	if (!native || typeof native !== 'object') {
		return native;
	}
	const cleaned = { ...native };
	for (const key of PROTECTED_NATIVE_KEYS) {
		delete cleaned[key];
	}
	return cleaned;
}

/**
 * Creates a new local backup of this instance (native config minus protected keys, plus
 * all objects/states under its own namespace) and prunes older backups.
 *
 * @param {object} adapter - The ioBroker adapter instance.
 * @returns {Promise<string>} The created backup's file name.
 */
async function createBackup(adapter) {
	const dir = await ensureBackupDir(adapter);
	const namespace = adapter.namespace;

	const instanceObject = await adapter.getForeignObjectAsync(`system.adapter.${namespace}`);
	const objects = (await adapter.getForeignObjectsAsync(`${namespace}.*`)) || {};

	const payload = {
		adapter: 'solectrus-influxdb',
		namespace,
		adapterVersion: ADAPTER_VERSION,
		createdAt: Date.now(),
		instanceNative: stripProtectedNative(instanceObject && instanceObject.native),
		objects,
	};

	const gz = zlib.gzipSync(Buffer.from(JSON.stringify(payload), 'utf8'));

	const stamp = new Date().toISOString().replace(/[:.]/g, '-');
	const fileName = `solectrus-influxdb_${namespace.split('.').pop()}_${stamp}${BACKUP_EXT}`;
	await fsp.writeFile(path.join(dir, fileName), gz);

	await pruneOldBackups(adapter);

	return fileName;
}

/**
 * Deletes a local backup file.
 *
 * @param {object} adapter - The ioBroker adapter instance.
 * @param {string} fileName - Backup file name as returned by {@link listBackups}.
 * @returns {Promise<void>}
 */
async function deleteBackup(adapter, fileName) {
	const safeName = sanitizeFileName(fileName);
	const dir = getBackupDir(adapter);
	await fsp.unlink(path.join(dir, safeName));
}

/**
 * Reads a local backup file for download.
 *
 * @param {object} adapter - The ioBroker adapter instance.
 * @param {string} fileName - Backup file name as returned by {@link listBackups}.
 * @returns {Promise<string>} The file content, base64-encoded.
 */
async function readBackupBase64(adapter, fileName) {
	const safeName = sanitizeFileName(fileName);
	const dir = getBackupDir(adapter);
	const buf = await fsp.readFile(path.join(dir, safeName));
	return buf.toString('base64');
}

function decodeBackupPayload(buf) {
	let json;
	try {
		json = zlib.gunzipSync(buf).toString('utf8');
	} catch (err) {
		throw new Error(`Not a valid SOLECTRUS InfluxDB backup archive: ${err.message}`);
	}
	let payload;
	try {
		payload = JSON.parse(json);
	} catch (err) {
		throw new Error(`Backup content is not valid JSON: ${err.message}`);
	}
	if (!payload || payload.adapter !== 'solectrus-influxdb') {
		throw new Error('Not a SOLECTRUS InfluxDB backup file');
	}
	return payload;
}

/**
 * Validates and stores a user-uploaded backup file.
 *
 * @param {object} adapter - The ioBroker adapter instance.
 * @param {string} fileName - Original file name chosen by the user.
 * @param {string} base64Content - The file content, base64-encoded.
 * @returns {Promise<string>} The stored backup's file name.
 */
async function saveUploadedBackup(adapter, fileName, base64Content) {
	const buf = Buffer.from(String(base64Content || ''), 'base64');
	decodeBackupPayload(buf); // validate before persisting anything

	const dir = await ensureBackupDir(adapter);
	const safeBase = path.basename(String(fileName || 'upload')).replace(/[^a-zA-Z0-9._-]/g, '_');
	const finalName = safeBase.endsWith(BACKUP_EXT) ? safeBase : `${safeBase}${BACKUP_EXT}`;
	await fsp.writeFile(path.join(dir, finalName), buf);

	await pruneOldBackups(adapter);

	return finalName;
}

/**
 * Restores all backed-up objects (folders/channels/states) for this instance.
 * The instance's native config is intentionally NOT applied here - the caller applies it
 * afterwards (see main.js), because writing it triggers an automatic instance restart via
 * js-controller and would otherwise race with the sendTo() response.
 *
 * @param {object} adapter - The ioBroker adapter instance.
 * @param {string} fileName - Backup file name as returned by {@link listBackups}.
 * @returns {Promise<{restoredCount: number, instanceNative: object|null}>} Restore result.
 */
async function restoreBackup(adapter, fileName) {
	const safeName = sanitizeFileName(fileName);
	const dir = getBackupDir(adapter);
	const buf = await fsp.readFile(path.join(dir, safeName));
	const payload = decodeBackupPayload(buf);

	const currentNamespace = adapter.namespace;
	const backupNamespace = payload.namespace || currentNamespace;
	const objects = payload.objects || {};

	let restoredCount = 0;
	for (const oldId of Object.keys(objects)) {
		const obj = objects[oldId];
		if (!obj || typeof obj !== 'object') {
			continue;
		}
		// Remap ids so a backup taken on e.g. solectrus-influxdb.0 can be restored into .1
		const newId =
			backupNamespace !== currentNamespace && oldId.startsWith(`${backupNamespace}.`)
				? currentNamespace + oldId.slice(backupNamespace.length)
				: oldId;
		try {
			await adapter.setObjectAsync(newId, { ...obj, _id: newId });
			restoredCount++;
		} catch (err) {
			adapter.log.warn(`Could not restore object "${newId}": ${err}`);
		}
	}

	return { restoredCount, instanceNative: payload.instanceNative || null };
}

module.exports = {
	BACKUP_EXT,
	PROTECTED_NATIVE_KEYS,
	getBackupDir,
	listBackups,
	createBackup,
	deleteBackup,
	readBackupBase64,
	saveUploadedBackup,
	restoreBackup,
};
